// fruitjam_library.h — Lisp Library content for Fruit Jam
// Loaded at boot when lisplibrary is defined.
// Uses C++ raw string literal as recommended by ulisp.com.
//
// NOTE: uLisp's reader does NOT treat ; as a line comment in the usual
// sense. It skips from ; to the next '(' character, which means any
// text containing parentheses after a ; will confuse the reader.
// Keep only pure Lisp forms inside the raw string — use C++ comments
// (outside the string) for documentation.

R"lisplibrary(

(defvar *key-up* 128)
(defvar *key-down* 129)
(defvar *key-left* 130)
(defvar *key-right* 131)
(defvar *key-home* 132)
(defvar *key-end* 133)
(defvar *key-pgup* 134)
(defvar *key-pgdn* 135)
(defvar *key-insert* 136)
(defvar *key-f1* 137)
(defvar *key-f2* 138)
(defvar *key-f3* 139)
(defvar *key-f4* 140)
(defvar *key-f5* 141)
(defvar *key-f6* 142)
(defvar *key-f7* 143)
(defvar *key-f8* 144)
(defvar *key-f9* 145)
(defvar *key-f10* 146)
(defvar *key-f11* 147)
(defvar *key-f12* 148)

(defvar *mod-ctrl* 17)
(defvar *mod-shift* 34)
(defvar *mod-alt* 68)
(defvar *mod-super* 136)

(defun key-code (k) (logand k 255))
(defun key-mod (k) (logand (ash k -8) 255))

(defvar *pkgs* nil)

(defun package-load (f)
  "Load and eval a Lisp file from SD, tracking new symbols as a package. Returns the list of new symbols."
  (package-unload f)
  (let ((before (globals)))
    (with-sd-card (s f)
      (loop (let ((form (read s)))
        (unless form (return))
        (eval form))))
    (let ((new (mapcan (lambda (s) (unless (member s before) (list s))) (globals))))
      (setf *pkgs* (cons (cons f new) *pkgs*))
      new)))

(defun package-save (f)
  "Save a loaded package's symbols back to file on SD as defun/defvar forms."
  (let ((pkg (assoc f *pkgs* :test #'string=)))
    (unless pkg (error "package not found: ~a" f))
    (with-sd-card (s f 2)
      (dolist (sym (cdr pkg))
        (let ((val (eval sym)))
          (if (and (consp val) (eq (car val) 'lambda))
            (pprint (cons 'defun (cons sym (cdr val))) s)
            (pprint (list 'defvar sym (list 'quote val)) s)))))))

(defun package-unload (f)
  "Unbind all symbols tracked by package f and remove it from *pkgs*."
  (let ((pkg (assoc f *pkgs* :test #'string=)))
    (when pkg
      (dolist (sym (cdr pkg)) (makunbound sym))
      (setf *pkgs* (mapcan (lambda (p) (unless (string= (car p) f) (list p))) *pkgs*)))))

(defun package-add (f sym)
  "Add symbol sym to package f's tracking list, creating the package if it doesn't exist. Returns sym."
  (let ((pkg (assoc f *pkgs* :test #'string=)))
    (unless pkg
      (setf *pkgs* (cons (cons f nil) *pkgs*))
      (setf pkg (car *pkgs*)))
    (unless (member sym (cdr pkg))
      (setf (cdr pkg) (cons sym (cdr pkg))))
    sym))

(defun package-remove (f sym &optional unbind)
  "Remove sym from package f's tracking list. If unbind is true, also makunbound sym. Returns sym."
  (let ((pkg (assoc f *pkgs* :test #'string=)))
    (unless pkg (error "package not found: ~a" f))
    (setf (cdr pkg) (mapcan (lambda (s) (unless (eq s sym) (list s))) (cdr pkg)))
    (when unbind (makunbound sym))
    sym))

(defun package-symbols (f)
  "Return the list of symbols tracked by package f."
  (let ((pkg (assoc f *pkgs* :test #'string=)))
    (unless pkg (error "package not found: ~a" f))
    (cdr pkg)))

(defun package-list ()
  "Return a list of all loaded package names (filenames)."
  (mapcar #'car *pkgs*))

(defun demo-leds (r g b)
  (dotimes (i 5)
    (pixels-set-pixel-color i r g b))
  (pixels-show))

(defun demo-ui (ci colors sz col)
  (let ((n (length colors)) (bw 16) (bh 12) (by 369))
    (let ((x 4))
      (dotimes (i n)
        (let ((c (nth i colors)))
          (fill-rect x by bw bh (car c))
          (when (= (car c) 0)
            (draw-rect x by bw bh 150))
          (if (= i ci)
            (draw-rect (- x 1) (- by 1) (+ bw 2) (+ bh 2) 223)
            (draw-rect (- x 1) (- by 1) (+ bw 2) (+ bh 2) 0))
          (setq x (+ x bw 3)))))
    (fill-rect 472 365 39 19 0)
    (if (= col 0)
      (draw-circle 492 374 sz 150)
      (fill-circle 492 374 sz col))
    (draw-rect 471 364 40 20 64)))

(defun demo-click (note)
  (audio-note 0 note 150))

(defun demo-blip ()
  (audio-note 1 84 100))

(defun demo ()
  (pixels-begin)
  (graphics-mode)
  (fill-screen 0)
  (let* ((colors '((223 255 255 255) (0 0 0 0) (192 255 0 0) (28 0 255 0)
                    (3 0 0 255) (220 255 255 0) (31 0 255 255)
                    (195 255 0 255) (208 255 128 0)
                    (150 170 170 170) (64 85 85 85)))
         (ci 0)
         (sz 3)
         (sizes '(1 3 6 10))
         (si 1)
         (col (car (nth ci colors)))
         (b2 nil) (b3 nil)
         (was-drawing nil))
    (set-cursor 184 4)
    (set-text-color 223 0)
    (set-text-size 2)
    (with-gfx (s) (princ "Fruit Jam" s))
    (set-text-size 1)
    (set-cursor 8 24)
    (set-text-color 150 0)
    (with-gfx (s) (princ "Mouse:draw c/B2:color s/B3:size x:clear Esc:quit" s))
    (draw-line 0 38 511 38 64)
    (draw-line 0 364 511 364 64)
    (demo-ui ci colors sz col)
    (let ((cc (nth ci colors)))
      (demo-leds (nth 1 cc) (nth 2 cc) (nth 3 cc)))
    (mouse-show)
    (keyboard-flush)
    (audio-wave 0 2) (audio-vol 0 15)
    (audio-wave 1 1) (audio-vol 1 10)
    (audio-wave 2 1) (audio-vol 2 100)
    (audio-envelope 2 10 150 80 300)
    (dolist (n '(60 64 67 72))
      (audio-note 2 n) (delay 200))
    (audio-release 2) (delay 400)
    (audio-stop 2) (audio-envelope 2 nil)
    (loop
      (let ((pressed (button 2)))
        (when (and pressed (not b2))
          (setq ci (mod (+ ci 1) (length colors)))
          (setq col (car (nth ci colors)))
          (demo-ui ci colors sz col)
          (let ((cc (nth ci colors)))
            (demo-leds (nth 1 cc) (nth 2 cc) (nth 3 cc)))
          (demo-click (+ 60 (* ci 2))))
        (setq b2 pressed))
      (let ((pressed (button 3)))
        (when (and pressed (not b3))
          (setq si (mod (+ si 1) (length sizes)))
          (setq sz (nth si sizes))
          (demo-ui ci colors sz col)
          (demo-click (+ 72 (* si 3))))
        (setq b3 pressed))
      (if (> (mouse-buttons) 0)
        (progn
          (let ((mx (mouse-x)) (my (mouse-y)))
            (when (and (> my 38) (< my 364))
              (if (> sz 1)
                (fill-circle mx my sz col)
                (draw-pixel mx my col))
              (unless was-drawing (demo-blip))))
          (setq was-drawing t))
        (setq was-drawing nil))
      (let ((k (keyboard)))
        (when k
          (let ((kc (key-code k)))
            (cond
              ((= kc 27)
                (mouse-hide)
                (audio-stop-all)
                (pixels-clear) (pixels-show)
                (text-mode)
                (return))
              ((or (= kc 99) (= kc 67))
                (setq ci (mod (+ ci 1) (length colors)))
                (setq col (car (nth ci colors)))
                (demo-ui ci colors sz col)
                (let ((cc (nth ci colors)))
                  (demo-leds (nth 1 cc) (nth 2 cc) (nth 3 cc)))
                (demo-click (+ 60 (* ci 2))))
              ((or (= kc 115) (= kc 83))
                (setq si (mod (+ si 1) (length sizes)))
                (setq sz (nth si sizes))
                (demo-ui ci colors sz col)
                (demo-click (+ 72 (* si 3))))
              ((or (= kc 120) (= kc 88))
                (fill-rect 0 39 512 325 0)
                (demo-click 48))))))
      (delay 8))))

)lisplibrary"
